Fix type annotation so it's ok in newest sphinx/autoapi
this otherwise gets
```
astroid.exceptions.InferenceError: Inference failed for all members of [<BinOp l.13 at 0x7fd379c99e80>].
```